apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  source:
    repoURL: https://github.com/defenseunicorns-labs/pepr-with-argo
    targetRevision: HEAD
    path: k8s/controller
  destination:
    server: https://kubernetes.default.svc
    namespace: pepr-system 
  project: default
  syncPolicy:
    automated: {}
